user registration
Slightly-Techie/st-school-api pull request #6
Opened 2023-10-01 18:39 UTC by kwamebio

2023-10-02 06:52 UTC, blitzblade requested changes

2023-10-02 06:52 UTC, blitzblade commented on app/models/user.rb
> +            self.amount = 100
1. I thought we agreed on "Full" and "Part" instead of that long string. 
2. The amount shouldn't be hard coded. Make it an env variable for now.

2023-10-02 06:52 UTC, blitzblade commented on db/migrate/20230925142120_create_users.rb
> +      t.string :stack
stack and language shouldn't be in users. Remember I created a stack table and a stack_options table? Use the text sent from the frontend to fetch those values and set their ids as stack_option_id for the user.

we can always trace that to the stack

2023-10-02 15:11 UTC, kwamebio commented on db/migrate/20230925142120_create_users.rb
> +      t.string :stack
I only put them there because of the attributes the frontend required when we had the hackathon. So with the approach you are talking about, I will be returning the stack_option_id in the response instead of the stack and stack option(language)

2023-10-05 14:45 UTC, blitzblade approved these changes

2023-10-05 14:46 UTC, blitzblade approved these changes

2023-10-05 14:46 UTC, blitzblade approved these changes

2023-10-05 14:46 UTC, merged